// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiEh--gmpqXLR5JcaWggsSWAIH5skR0C8',
    appId: '1:975706175700:web:71da2267266eef34a32341',
    messagingSenderId: '975706175700',
    projectId: 'nnikolovskiii',
    authDomain: 'nnikolovskiii.firebaseapp.com',
    storageBucket: 'nnikolovskiii.appspot.com',
    measurementId: 'G-6TE27QSNR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5sL4HSFENeDBMUQiAWPHHSNUTTOMDT3E',
    appId: '1:975706175700:android:48181908cbda9eefa32341',
    messagingSenderId: '975706175700',
    projectId: 'nnikolovskiii',
    storageBucket: 'nnikolovskiii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEAU28-d_PSroux_0EZE1CQYvt1M4R7rc',
    appId: '1:975706175700:ios:6db6ed15ab23d3a3a32341',
    messagingSenderId: '975706175700',
    projectId: 'nnikolovskiii',
    storageBucket: 'nnikolovskiii.appspot.com',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEAU28-d_PSroux_0EZE1CQYvt1M4R7rc',
    appId: '1:975706175700:ios:9fb57517eca9cd10a32341',
    messagingSenderId: '975706175700',
    projectId: 'nnikolovskiii',
    storageBucket: 'nnikolovskiii.appspot.com',
    iosBundleId: 'com.example.lab3.RunnerTests',
  );
}
